### ISSUE TITLE
getUserId index should not be a ZCTextIndex!

### ISSUE THREAD

**Issue by agitator** [collective/Products.membrane#5]
This ends up in very weird sideeffects...
In my case the password reset mechanism didn't work properly, because the userid that was searched for wasn't found and no IMembraneUserChanger could be looked up. Seems the stemming mechanism of ZCTextIndex was able to find "special" groups of characters to index, instead of indexing the whole userid string.

Does anyone know why this index was used in the first place?
Otherwise I'd change it to a FieldIndex.

kudos to @jensens

**Comment by saily** [comment]
I think a `ZCTextIndex` was choosen to have better search on usernames/userids. 
But from my point of view it's an issue if we use this search index to lookup items.

As far as i remember there is are `FieldIndex` in `membrane_tool` which index the exact value.

- `exact_getGroupId (indexed attributes: getGroupId)` - FieldIndex
- `exact_getUserId (indexed attributes: getUserId)` - FieldIndex
- `exact_getUserName (indexed attributes: getUserName)` - FieldIndex

Passwort reset should of course lookup the id/username using one of the `exact_*` indexes.

**Comment by jensens** [comment]
Hmm, I think the opposite would make more semantic sense, usally I'd expect an Index to just work w/o any fuzziness::

getUserId -> Fieldindex
search_getUserId -> ZCTextIndex

and the main issue over all is, that the utils methods are using the fuzzy index and thus this becomes an theoretical security issue, because its - in theory - possible to take over (accidentially) a foreign account if the match is not exact.

So the real bug is that a fuzzy getUserId query is initiated here:
https://github.com/collective/Products.membrane/blob/master/Products/membrane/plugins/usermanager.py#L260

**Comment by agitator** [comment]
fixed with https://github.com/collective/Products.membrane/commit/603290971bfeab297d5589223d70259d935e31c3

**Comment by saily** [comment]
cool, thanks!

**Comment by mauritsvanrees** [comment]
I have released 2.1.12 with this fix. Thanks.

**Comment by agitator** [comment]
Thanx!
